---

- name: Check if Apache already installed
  stat: path=/etc/init.d/apache2
  register: status

- name: Installing Apache
  apt: name={{item}} state=present update_cache=yes 
  when: not status.stat.exists
  with_items: 
    - apache2
    - python

  notify: 
    - apache2 restart
