---
# tasks file for git
- name: install git on ubuntu
  apt:
    pkg: git
    state: present
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name : install git on centos
  yum:
    pkg: git
    state: present
  when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
